### ISSUE TITLE
Request failed Request body doesn't fulfill schema

### ISSUE THREAD

**Issue by githublti** [tlhackque/getssl#1]
I'm currently using the getssl shell scripts along with GoDaddy to create SSL certificates via LetsEncrypt.  The version of the script is 

getssl ver. 2.10

This has been working fine.  Today, I went to issue a new certificate for an internal chat server and get the error:

Registering account
Verify each domain
Verifying chat.ltiprinting.com
Request failed Request body doesn't fulfill schema, see details in `fields`
getssl: DNS_ADD_COMMAND failed for domain chat.ourhiddendomain.com

Doug

**Comment by tlhackque** [comment]
I'm just seeing this now - in 2021 - since this repo is generally used for local changes, eventually pushed upstream.  

I assume the issue has been resolved upstream.

I'll disable issues to prevent future confusion.
